/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*	LIB	*/
#include <stdio.h>
#include "BIT_MATH.h"
#include "STD_TYPES.h"
#include "TEMPDELAY.h"
/*	MCAL	*/
#include "GPIO_interface.h"
#include "RCC_interface.h"
#include "NVIC_interface.h"
#include "SCB_interface.h"
#include "EXTI_interface.h"
#include "SYSCFG_interface.h"
/*	HAL	*/
#include "SEVENSEGMENT_interface.h"
#include "LCD_interface.h"
#include "KEYPAD_interface.h"

void fooFunc(void)
{
	DIO_voidTogglePinOutputLevel(DIO_PORT_A, 2);
}

int main(void)
{
	/*	init RCC	*/
	RCC_voidSysClockInit(
		true, false, true, false,
		true,
		RCC_SYSCLOCKSWITCH_HSI,
		RCC_PLLSOURCE_HSI,
		100,
		8,
		RCC_PLLDEVISIONFACTOR_8
		);

	/*	RCC enable peripheral GPIOA, SYSCFG	*/
	RCC_voidEnablePeripheralClk(RCC_PERIPHERAL_GPIOA);
	RCC_voidEnablePeripheralClk(RCC_PERIPHERAL_GPIOB);
	RCC_voidEnablePeripheralClk(RCC_PERIPHERAL_SYSCFG);

	/*	init pins	*/
	/*	B0 is Input Internal Pull up	*/
	DIO_voidSetPinMode(DIO_PORT_B, 0, DIO_MODE_input);
	DIO_voidSetPinPull(DIO_PORT_B, 0, DIO_PULL_up);
	/*	A2 is Output Push Pull		*/
	DIO_voidSetPinMode(DIO_PORT_A, 2, DIO_MODE_GPO);

	/*	system control block	*/
	MSCB_voidSetPriorityGroupsAndSubGroupsNumber(MSCB_PRIGROUP_group0_sub16);

	/*	SYSCFG choose source port of line	*/
	MSYSCFG_voidSetEXTILineSource(0, DIO_PORT_B);


	/*	enable NVIC	interrupt	*/
	MNVIC_voidEnableInterrupt(MNVIC_INTERRUPT_EXTI0);
	/*	clear pending flag	*/
	MNVIC_voidSetPendingFlag(MNVIC_INTERRUPT_EXTI0);

	/*	EXTI	*/
	MEXTI_voidSetCallBack(0, fooFunc);
	MEXTI_voidEnableLine(0);
	MEXTI_voidSetTriggeringEdge(0, MEXTI_TRIGGER_bothEdges);

	while(1)
	{

	}
}
