/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

#include "LIB/BIT_MATH.h"
#include "LIB/STD_TYPES.h"
#include "MCAL/GPIO/GPIO_interface.h"
#include "MCAL/RCC/RCC_interface.h"
#include "HAL/SEVENSEGMENT/SEVENSEGMENT_interface.h"
#include "HAL/LCD/LCD_interface.h"
#include "TEMPDELAY.h"
#include "HAL/KEYPAD/KEYPAD_interface.h"

int main(void)
{
	RCC_voidSysClockInit(
		true, false, true, false,
		true,
		RCC_SYSCLOCKSWITCH_HSI,
		RCC_PLLSOURCE_HSI,
		100,
		8,
		RCC_PLLDEVISIONFACTOR_8
		);

	/*	RCC enable peripheral GPIOA, GPIOB	*/
	RCC_voidEnablePeripheralClk(RCC_PERIPHERAL_GPIOA);
	RCC_voidEnablePeripheralClk(RCC_PERIPHERAL_GPIOB);

	/*	init 7-segment object	*/
	SEVENSEGMENT_t ss;
	DIO_PIN pins[] = {
		DIO_PIN_B0, DIO_PIN_B1, DIO_PIN_B2, DIO_PIN_B5,
		DIO_PIN_B6, DIO_PIN_B7, DIO_PIN_B8
	};
	SEVENSEGMENT_voidInit(
		&ss, SEVENSEGMENT_COMTYPE_cathode, pins,
		SEVENSEGMENT_POINTCONNECTION_notConnected, DIO_OUTPUTSPEED_veryHigh
		);

	/*	init keypad object	*/
	DIO_PIN rowPins[] = {DIO_PIN_A7, DIO_PIN_A6, DIO_PIN_A5, DIO_PIN_A4};
	DIO_PIN colPins[] = {DIO_PIN_A3, DIO_PIN_A2, DIO_PIN_A1, DIO_PIN_A0};
	s8 buttons[][4] = {
		{'1', '2', '3', 'A'},
		{'4', '5', '6', 'B'},
		{'7', '8', '9', 'C'},
		{'*', '0', '#', 'D'}
	};
	KEYPAD_t keypad;
	KEYPAD_voidInit(&keypad, 4, 4, rowPins, colPins, buttons, 200, DIO_OUTPUTSPEED_veryHigh);


	s8 ch;
	while(1)
	{
		ch = KEYPAD_s8GetPress(&keypad);
		SEVENSEGMENT_voidWrite(&ss, ch-'0', false);
	}
}
